{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage }}
  storageClassName: {{ .Values.elasticsearch.storageClassName }}
{{- end }}
